--[[
    FSSHUB Main Menu
    Monolithic UI Entry Point
    
    This file is the PUBLIC entry point loaded via loadstring from GitHub.
    It expects FSSHUB_INFO to be injected by the Worker before execution.
    
    Build: This file is generated by combining Fluent library + FSSHUB Bridge
    Obfuscation: Apply obfuscator to this file before distribution
    
    GitHub: https://github.com/fingerscrows/fsshub-assets
]]

-- Ensure context exists
if not getgenv().FSSHUB_INFO then
    warn("[FSSHUB] Error: FSSHUB_INFO not found. This script must be loaded via FSSHUB Worker.")
    return
end

local Info = getgenv().FSSHUB_INFO
print("[FSSHUB] Main Menu initializing...")
print("[FSSHUB] User:", Info.User.Username, "| Tier:", Info.User.Tier)

-- Load bundled Fluent library
-- NOTE: In production, this will be replaced with the bundled Fluent code
-- For development, we load from GitHub
local Fluent = loadstring(game:HttpGet("https://github.com/dawid-scripts/Fluent/releases/latest/download/main.lua"))()
local SaveManager = loadstring(game:HttpGet("https://raw.githubusercontent.com/dawid-scripts/Fluent/master/Addons/SaveManager.lua"))()
local InterfaceManager = loadstring(game:HttpGet("https://raw.githubusercontent.com/dawid-scripts/Fluent/master/Addons/InterfaceManager.lua"))()

-- ========== EVENT SYSTEM ==========
local Events = {
    listeners = {},
    Emit = function(self, eventName, ...)
        local callbacks = self.listeners[eventName]
        if callbacks then
            for _, callback in ipairs(callbacks) do
                local success, err = pcall(callback, ...)
                if not success then
                    warn("[FSSHUB Events] Error:", err)
                end
            end
        end
    end,
    On = function(self, eventName, callback)
        self.listeners[eventName] = self.listeners[eventName] or {}
        table.insert(self.listeners[eventName], callback)
    end
}
_G.FSSHUB_EVENTS = Events

-- ========== CONTEXT PARSING ==========
local isPremium = Info.User.IsPremium or false
local username = Info.User.Username or "User"
local tier = Info.User.Tier or "Free"
local expiryText = Info.User.ExpiryText or "Never"
local gameName = Info.Game.Name or "Universal"
local gameSlug = Info.Game.Slug or "unknown"
local isSupported = Info.Game.IsSupported or false
local version = Info.Version or "v1.0.0"

-- ========== CREATE WINDOW ==========
local Window = Fluent:CreateWindow({
    Title = "FSSHUB | " .. gameName,
    SubTitle = version,
    TabWidth = 160,
    Size = UDim2.fromOffset(580, 460),
    Acrylic = true,
    Theme = "Amethyst",
    MinimizeKey = Enum.KeyCode.LeftControl
})

-- ========== TABS ==========
local Tabs = {
    Home = Window:AddTab({ Title = "Dashboard", Icon = "home" }),
    Universal = Window:AddTab({ Title = "Universal", Icon = "globe" }),
    Game = Window:AddTab({ Title = gameName, Icon = "gamepad-2" }),
    Settings = Window:AddTab({ Title = "Settings", Icon = "settings" })
}

local Options = Fluent.Options

-- ========== HOME TAB ==========
Tabs.Home:AddParagraph({
    Title = "Welcome, " .. username .. (isPremium and " 👑" or ""),
    Content = "Tier: " .. tier .. "\nExpires: " .. expiryText
})

if isSupported then
    Tabs.Home:AddParagraph({
        Title = "Game Detected",
        Content = gameName .. " (" .. gameSlug .. ")"
    })
else
    Tabs.Home:AddParagraph({
        Title = "Universal Mode",
        Content = "No game-specific features for this game"
    })
end

Tabs.Home:AddParagraph({
    Title = "Script Info",
    Content = "Version: " .. version .. "\nPowered by Fluent UI"
})

-- ========== UNIVERSAL TAB ==========
local speedEnabled = false
local speedValue = 16

Tabs.Universal:AddToggle("SpeedWalk", {
    Title = "Walk Speed",
    Description = "Modify character walk speed",
    Default = false
})

Options.SpeedWalk:OnChanged(function()
    speedEnabled = Options.SpeedWalk.Value
    Events:Emit("toggle_speed", speedEnabled, speedValue)
end)

Tabs.Universal:AddSlider("SpeedValue", {
    Title = "Speed Value",
    Description = "16 - 200",
    Default = 16,
    Min = 16,
    Max = 200,
    Rounding = 0,
    Callback = function(value)
        speedValue = value
        if speedEnabled then
            Events:Emit("toggle_speed", true, value)
        end
    end
})

-- Premium Features
if isPremium then
    local jumpEnabled = false
    local jumpValue = 50
    
    Tabs.Universal:AddToggle("JumpPower", {
        Title = "Jump Power 👑",
        Description = "Modify character jump power (Premium)",
        Default = false
    })
    
    Options.JumpPower:OnChanged(function()
        jumpEnabled = Options.JumpPower.Value
        Events:Emit("toggle_jump", jumpEnabled, jumpValue)
    end)
    
    Tabs.Universal:AddSlider("JumpValue", {
        Title = "Jump Value 👑",
        Description = "50 - 300",
        Default = 50,
        Min = 50,
        Max = 300,
        Rounding = 0,
        Callback = function(value)
            jumpValue = value
            if jumpEnabled then
                Events:Emit("toggle_jump", true, value)
            end
        end
    })
else
    Tabs.Universal:AddParagraph({
        Title = "🔒 Premium Features Locked",
        Content = "Upgrade to Premium to unlock:\n• Jump Power\n• And more coming soon!"
    })
end

-- ========== GAME TAB ==========
-- Placeholder - Worker will inject game-specific features
Tabs.Game:AddParagraph({
    Title = "Game Features",
    Content = "Loading " .. gameName .. " features..."
})

-- ========== SETTINGS TAB ==========
SaveManager:SetLibrary(Fluent)
InterfaceManager:SetLibrary(Fluent)

SaveManager:IgnoreThemeSettings()
SaveManager:SetIgnoreIndexes({})

InterfaceManager:SetFolder("FSSHUB")
SaveManager:SetFolder("FSSHUB/" .. gameSlug)

InterfaceManager:BuildInterfaceSection(Tabs.Settings)
SaveManager:BuildConfigSection(Tabs.Settings)

-- ========== EXPOSE GLOBALS ==========
_G.FSSHUB_TABS = Tabs
_G.FSSHUB_WINDOW = Window
_G.FSSHUB_FLUENT = Fluent
_G.FSSHUB_OPTIONS = Options

-- ========== SELECT DEFAULT TAB ==========
Window:SelectTab(1)

-- ========== WELCOME NOTIFICATION ==========
Fluent:Notify({
    Title = "FSSHUB",
    Content = "Welcome, " .. username .. "!",
    SubContent = tier .. " | " .. version,
    Duration = 5
})

print("[FSSHUB] Main Menu loaded successfully")
print("[FSSHUB] Tabs and Events exposed to global scope")

-- Load saved config
SaveManager:LoadAutoloadConfig()
